theme = "harbor"
baseURL = "https://nullrequest.com/"
languageCode = "en-us"
title = "Null's blog"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = "null-s-blog"
enableRobotsTXT = true
canonifyURLs = true
[permalinks]
    posts = "/:filename"

[Author]
  name = "Nullrequest"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fa-solid fa-user fa-lg"
  url = "/about/"
  weight = 3
  aria_label = "This is a link to my about page, the icon is the no picture icon on facebook"

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3
  aria_label="This is a link to the search page. The icon is the magnifine glass"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"
  FontAwesomeURL = "https://kit.fontawesome.com/beafef2608.js"
  [params.logo]
    url = "iconx50.webp" # static/images/
    width = 50
    height = 50
    alt = "Logo"

[[params.social]]
  name="instagram"
  url="https://www.instagram.com/nullrequest_/"
  icon="fab fa-instagram fa-2x"
  aria_label="A link to my instagram account"

[[params.social]]
  name="mastodon"
  url="https://hachyderm.io/@lunarequest"
  icon="fa-brands fa-mastodon fa-2x"
  aria_label="My mastodon where i'm most active"

[[params.social]]
  name="mail"
  url="mailto:luna.dragon@suse.com"
  icon="fas fa-envelope-open-text fa-2x"
  aria_label="Email my if you like the old school stuff"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
