theme = "harbor"
baseURL = "https://www.nullblog.netlify.app/"
languageCode = "en-us"
title = "Null's blog"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[permalinks]
    posts = "/:filename"

[Author]
  name = "Nullrequest"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3


[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3


[params.logo]
  url = "icon.png" # static/images/icon.png
  width = 50
  height = 50
  alt = "Logo"
[taxonomies]
  category = "categories"
  tag = "tags"
